// frontend/react-src/components/common/http-headers-grid.tsx
import { getLatestHTTPRequestHeaderEntries, getLatestHTTPResponseHeaderEntries } from '@/lib/result'

export function HttpHeadersGrid({ resultData }: { resultData: unknown }) {
  const requestHeaders = getLatestHTTPRequestHeaderEntries(resultData)
  const responseHeaders = getLatestHTTPResponseHeaderEntries(resultData)

  if (!requestHeaders.length && !responseHeaders.length) {
    return null
  }

  return (
    <div className="grid gap-4 lg:grid-cols-2">
      <HeaderCard title="Request Headers" entries={requestHeaders} />
      <HeaderCard title="Response Headers" entries={responseHeaders} />
    </div>
  )
}

function HeaderCard({
  title,
  entries,
}: {
  title: string
  entries: Array<{ name: string; value: string }>
}) {
  return (
    <div className="rounded-sm border border-[var(--border)] bg-[var(--surface-2)] p-4">
      <div className="mb-3 text-xs uppercase tracking-[0.08em] text-[var(--text-3)]">{title}</div>
      {entries.length ? (
        <div className="space-y-2">
          {entries.map(entry => (
            <div
              key={`${title}-${entry.name}`}
              className="rounded-sm border border-[var(--border)] bg-[var(--surface)] px-3 py-2"
            >
              <div className="text-xs font-semibold text-[var(--text-2)]">
                {entry.name}
              </div>
              <div className="mt-1 break-all text-sm">{entry.value}</div>
            </div>
          ))}
        </div>
      ) : (
        <div className="text-sm text-[var(--text-2)]">-</div>
      )}
    </div>
  )
}

// frontend/src/components/HttpHeadersGrid.vue
<template>
  <div class="http-headers-grid">
    <div class="http-headers-card">
      <h4>{{ $t('results.requestHeaders') }}</h4>
      <div v-if="requestHeaders.length > 0" class="http-header-list">
        <div
          v-for="entry in requestHeaders"
          :key="`req-${keyPrefix}-${entry.name}`"
          class="http-header-item"
        >
          <span class="http-header-name">{{ entry.name }}</span>
          <span class="http-header-value">{{ entry.value }}</span>
        </div>
      </div>
      <div v-else class="http-header-empty">-</div>
    </div>

    <div class="http-headers-card">
      <h4>{{ $t('results.responseHeaders') }}</h4>
      <div v-if="responseHeaders.length > 0" class="http-header-list">
        <div
          v-for="entry in responseHeaders"
          :key="`resp-${keyPrefix}-${entry.name}`"
          class="http-header-item"
        >
          <span class="http-header-name">{{ entry.name }}</span>
          <span class="http-header-value">{{ entry.value }}</span>
        </div>
      </div>
      <div v-else class="http-header-empty">-</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { getLatestHTTPRequestHeaderEntries, getLatestHTTPResponseHeaderEntries } from '@/utils/result'

const props = withDefaults(defineProps<{
  resultData?: unknown
  keyPrefix?: string
}>(), {
  resultData: undefined,
  keyPrefix: '',
})

const { t: $t } = useI18n()

const requestHeaders = computed(() => getLatestHTTPRequestHeaderEntries(props.resultData))
const responseHeaders = computed(() => getLatestHTTPResponseHeaderEntries(props.resultData))
</script>

<style scoped>
.http-headers-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
  margin-top: 12px;
}

.http-headers-card {
  border: 1px solid var(--border);
  border-radius: 10px;
  background: var(--surface-2);
  padding: 12px;
}

.http-headers-card h4 {
  margin: 0 0 8px;
  font-size: 13px;
  font-weight: 600;
  color: var(--text);
}

.http-header-list {
  display: grid;
  gap: 8px;
}

.http-header-item {
  display: grid;
  gap: 4px;
}

.http-header-name {
  font-size: 12px;
  color: var(--text);
  font-weight: 600;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, monospace;
}

.http-header-value {
  font-size: 12px;
  color: var(--text-2);
  word-break: break-all;
}

.http-header-empty {
  color: var(--text-2);
  font-size: 13px;
}

@media (max-width: 900px) {
  .http-headers-grid {
    grid-template-columns: 1fr;
  }
}
</style>
