// frontend/react-src/components/layout/top-bar.tsx
import * as DropdownMenu from '@radix-ui/react-dropdown-menu'
import { Languages, MoonStar, SunMedium } from 'lucide-react'
import { useMemo } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { Button } from '@/components/ui/button'
import { setLocale, type SupportedLocale } from '@/i18n'
import { cn } from '@/lib/cn'
import { useAppStore } from '@/state/app-store'

export function TopBar() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const location = useLocation()
  const theme = useAppStore(state => state.theme)
  const setTheme = useAppStore(state => state.setTheme)
  const locale = useAppStore(state => state.locale)
  const setStoreLocale = useAppStore(state => state.setLocale)

  const localeItems = useMemo(
    () => [
      { label: t('common.locale.zh'), value: 'zh-CN' as SupportedLocale },
      { label: t('common.locale.en'), value: 'en-US' as SupportedLocale },
    ],
    [t]
  )

  if (location.pathname === '/login') return null

  const isDark = theme === 'dark'

  async function handleLocaleChange(next: SupportedLocale) {
    setStoreLocale(next)
    setLocale(next)
  }

  return (
    <header className="sticky top-0 z-40 border-b border-stone-200 bg-[var(--surface)] dark:border-stone-700 dark:bg-[var(--surface)]">
      <div className="mx-auto flex h-16 w-full max-w-[1180px] items-center justify-between px-4 md:px-8">
        <button
          type="button"
          className="flex items-center gap-4 rounded-sm px-1 py-1 text-left outline-none"
          onClick={() => navigate('/test')}
          data-testid="topbar"
        >
          <div>
            <div className="text-sm font-semibold tracking-tight text-stone-950 dark:text-stone-50">
              Atlas
            </div>
            <div className="text-xs text-stone-500 dark:text-stone-400">
              Distributed network tests
            </div>
          </div>
        </button>

        <div className="flex items-center gap-2">
          <Button
            variant="ghost"
            size="sm"
            title={isDark ? t('home.themeLight') : t('home.themeDark')}
            onClick={() => setTheme(isDark ? 'light' : 'dark')}
          >
            {isDark ? <SunMedium className="h-4 w-4" /> : <MoonStar className="h-4 w-4" />}
          </Button>

          <DropdownMenu.Root>
            <DropdownMenu.Trigger asChild>
              <Button variant="secondary" size="sm" className="gap-2">
                <Languages className="h-4 w-4" />
                <span className="hidden sm:inline">
                  {localeItems.find(item => item.value === locale)?.label || locale}
                </span>
              </Button>
            </DropdownMenu.Trigger>
            <DropdownMenu.Portal>
              <DropdownMenu.Content
                sideOffset={8}
                align="end"
                className="z-[70] min-w-40 rounded-sm border border-stone-300 bg-[var(--surface)] p-1.5 dark:border-stone-700 dark:bg-[var(--surface)]"
              >
                {localeItems.map(item => (
                  <DropdownMenu.Item
                    key={item.value}
                    onClick={() => void handleLocaleChange(item.value)}
                    className={cn(
                      'cursor-pointer rounded-sm px-3 py-2 text-sm outline-none hover:bg-stone-100 dark:hover:bg-stone-800',
                      item.value === locale && 'bg-stone-100 dark:bg-stone-800'
                    )}
                  >
                    {item.label}
                  </DropdownMenu.Item>
                ))}
              </DropdownMenu.Content>
            </DropdownMenu.Portal>
          </DropdownMenu.Root>
        </div>
      </div>
    </header>
  )
}

// frontend/src/components/TopBar.vue
<template>
  <header
    v-if="showTopBar"
    class="topbar"
    data-testid="topbar"
  >
    <div class="topbar-inner">
      <div
        class="brand"
        @click="router.push('/')"
      >
        <span class="brand-text">Atlas</span>
      </div>

      <div class="actions">
        <!-- 主题切换按钮 -->
        <v-btn
          icon
          :title="isDark ? $t('home.themeLight') : $t('home.themeDark')"
          variant="text"
          size="small"
          @click="toggleTheme"
        >
          <v-icon>{{ isDark ? 'mdi-weather-sunny' : 'mdi-weather-night' }}</v-icon>
        </v-btn>

        <!-- 语言选择器（按钮 + 菜单） -->
        <v-menu>
          <template #activator="{ props }">
            <v-btn
              v-bind="props"
              variant="text"
              size="small"
              class="locale-btn"
              :title="$t('common.locale.select')"
            >
              <v-icon>mdi-translate</v-icon>
              <span class="locale-label">{{ currentLocaleLabel }}</span>
              <v-icon size="18">
                mdi-chevron-down
              </v-icon>
            </v-btn>
          </template>

          <v-list density="compact">
            <v-list-item
              v-for="it in localeItems"
              :key="it.value"
              @click="onChangeLocale(it.value)"
            >
              <v-list-item-title>{{ it.label }}</v-list-item-title>
            </v-list-item>
          </v-list>
        </v-menu>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { useTheme } from 'vuetify'

import type { SupportedLocale } from '@/i18n'
import { setLocale as applyLocale, getInitialLocale } from '@/i18n'

const route = useRoute()
const router = useRouter()
const { t: $t, locale: i18nLocale } = useI18n()
const theme = useTheme()

const showTopBar = computed(() => route.path !== '/login')

const locale = ref<SupportedLocale>(getInitialLocale())
const isDark = computed(() => theme.global.name.value === 'dark')

const THEME_KEY = 'atlas_theme'

function toggleTheme() {
  const next = isDark.value ? 'light' : 'dark'
  theme.global.name.value = next

  // 同步 HTML class
  const root = document.documentElement
  root.classList.toggle('dark', next === 'dark')
  root.dataset.theme = next

  try {
    window.localStorage.setItem(THEME_KEY, next)
  } catch {
    // ignore
  }
}

const localeItems = computed(() => [
  { label: String($t('common.locale.zh')), value: 'zh-CN' as SupportedLocale },
  { label: String($t('common.locale.en')), value: 'en-US' as SupportedLocale },
])

const currentLocaleLabel = computed(() => {
  return localeItems.value.find((it) => it.value === locale.value)?.label || ''
})

watch(
  () => i18nLocale.value,
  (v) => {
    locale.value = v as SupportedLocale
  },
  { immediate: true }
)

async function onChangeLocale(next: SupportedLocale) {
  await applyLocale(next)
}
</script>

<style scoped>
.topbar {
  height: 56px;
  display: flex;
  align-items: center;
  border-bottom: 1px solid var(--border);
  background: var(--surface);
}

.topbar-inner {
  width: 100%;
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 24px;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.brand {
  display: flex;
  align-items: center;
  cursor: pointer;
  user-select: none;
}

.brand-text {
  font-size: 18px;
  font-weight: 700;
}

.actions {
  display: flex;
  align-items: center;
  gap: 12px;
}

.locale-btn {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  color: var(--text);
}

.locale-label {
  font-size: 13px;
  color: var(--text-2);
}

@media (max-width: 720px) {
  .locale-label {
    display: none;
  }

  .actions {
    gap: 8px;
  }
}
</style>
